server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: update
         

  datasource:

    url: jdbc:mysql://localhost:3306/schedularapp
    username: root
    password: root

  task:
    scheduling:
      pool:
        size: 10